### ISSUE TITLE
Workaround mobile browsers?

### ISSUE THREAD

**Issue by thomasduenser** [jaysalvat/buzz#100]
Hello,

first of all - buzz is awesome! Thanks for the great work!

I'm aware of the fact, that we need a user interaction on mobile browsers to play the sounds as stated in your documentation. Is there a hack / workaround to make it still possible?

**My scenario**:
User Interaction -> load sound via SoundCloud API -> set up buzz object and play. This does not work mobile although this all happens when the user clicks on a specific element. I think that the problem is that I'm loading the sound with the SoundCloud API.

Can I fake a user interaction?

Thanks in advance for the help!
Thomas

**Comment by jaysalvat** [comment]
Hello :)

As far as I know, unfortunately, no.

**Comment by thomasduenser** [comment]
Thank you for the fast response. It seems to be my mistake, right? Your demo page is working on mobile browsers. Do I understand it correct -> for each sound I want to play, I need a user interaction. This means, there's no possibility to play 5 different songs one after another automatically after the first user interaction?

**Comment by jaysalvat** [comment]
Yes you need user interaction. 
As far as I know, you can't play 5 different songs one after another automatically.
No autoplay or even preload are allowed.

Regards.
