### ISSUE TITLE
Is it possible to disable error messages in the console window?

### ISSUE THREAD

**Issue by JohnAReid** [jaysalvat/buzz#102]
Minor niggle - but I just do not like error messages going to the console window when the code already knows about the error.

 In this particular case, the code is using the "sourceerror" to check for errors when it cannot load the request URL, but buzz will still print 
404 (Not Found)   buzz.min.js.11

So I was wondering if there is some way to turn off the error messages?

**Comment by jaysalvat** [comment]
Hello :)

There is no built-in way to not display those messages.
Buzz itself doesn't print any message and sourceerror is checked to pass the error as an event on buzz object.

Regards.
