### ISSUE TITLE
Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.

### ISSUE THREAD

**Issue by JohnAReid** [jaysalvat/buzz#103]
I know this has been raised before and that android requires a user gesture i.e  a tap. The issue I have is that I cannot trap the error by putting the buzz.play() in a try catch. This makes the whole website disabled.

Is there any way of trapping this error?

**Comment by jaysalvat** [comment]
Hello, no sorry, I don't know how.

I'm interested in if you find something.

**Comment by JohnAReid** [comment]
Yes I know it is a problem with Android and I have ended up putting a test in my code to see if running on Android and if then bring up a modal window with a button.

I wonder if  wrapping the code which calls the play method i.e. line 89 of buzz/src/buzz.js

this.sound.play();

in a try catch would help?

**Comment by jaysalvat** [comment]
Please make some tests and tell me.
Thanks.

**Comment by JohnAReid** [comment]
OK - will try and it out tomorrow and let you know.

**Comment by JohnAReid** [comment]
I tried wrapping the line 89 in a try catch statement and it failed to catch the error when running in android - most annoying!

**Comment by jaysalvat** [comment]
Sad :'(

Thanks for you contribution anyway.

**Comment by apfelbox** [comment]
@JohnAReid [if I read it correctly](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play#Return_value), `play()` returns a promise, with which you should be able to catch the error:

```
this.sound.play()
    .then(null, function () { ... });
```

**Comment by JohnAReid** [comment]
@apfelbox I give it another try and see if the promise returns an error. It will take a while as I have to make a separate version of my web site with the auto sound call - and then test it on Android tablet.

**Comment by JohnAReid** [comment]
@apfelbox - tested it out but no change - I suspect the html5 code is not registering the error back to js code.
