### ISSUE TITLE
pass buzz instance to callbacks instead of overriding this context

### ISSUE THREAD

**Issue by raygesualdo** [jaysalvat/buzz#106]
Right now, adding callbacks for events is not as clean as it could be, for instance, when working in an environment where `this` is already being used. Below is a trivial example inside a React.js component: 

```javascript
componentWillMount() {
  const sound = new buzz.sound(/* url */);
  sound.bind('timeupdate', function() {
    this.setState({ // notice collision
      time: buzz.toTimer(this.getTime()) //notice collision
    });
  });
}
```

When creating listeners for events, it would be helpful to allow the developer to determine what `this` is by the function type used. Passing the buzz instance would allow this to happen easily. Below is the code above rewritten with an example implementation:

```javascript
componentWillMount() {
  const sound = new buzz.sound(/* url */);
  sound.bind('timeupdate', function(buzzInstance, event) {
    this.setState({ // no more collision! incorrect this!
      time: buzz.toTimer(buzzInstance.getTime()) // no more collision!
    });
  });
}
```

Now, IIRC, the above code still wouldn't get me what I want since event listener callbacks override the `this` context as well, but arrow functions let the developer choose what `this` will be. Below is the rewritten example, but with an arrow function to preserve `this`:

```javascript
componentWillMount() {
  const sound = new buzz.sound(/* url */);
  sound.bind('timeupdate', (buzzInstance, event) => {
    this.setState({ // no more collision! correct this!
      time: buzz.toTimer(buzzInstance.getTime()) // no more collision!
    });
  });
}
```

From what I see in the source file, this change could be made by refactoring this code:

```javascript
var self = this,
  efunc = function (e) { func.call(self, e); };
// ...
events.push({ idx: idx, func: efunc });
```

First, we'll add a currying function: 

```javascript
function curryBuzzCallback (buzzInstance, func) {
  return function (event) {
    func(buzzInstance, event);
  }
}
```

Then we'll rewrite the code snippet to:

```javascript
var curriedFunc = curryBuzzCallback(this, func);
//...
events.push({ idx: idx, func: curriedFunc });
```

I realize minor changes would also have to be made around [this line](https://github.com/jaysalvat/buzz/blob/master/src/buzz.js#L496), [this line](https://github.com/jaysalvat/buzz/blob/master/src/buzz.js#L613) and [this line](https://github.com/jaysalvat/buzz/blob/master/src/buzz.js#L616). I am planning on forking and adding this change, but would love to PR the change as well to get it back into the primary repo and on npm.

Thoughts?

**Comment by jaysalvat** [comment]
Hello and thanks for the feed back.
There is no need to modify the library to me.

## With function

```javascript
componentWillMount() {        
    const sound = new buzz.sound('song.mp3');
    const self = this;
    
    sound.bind('timeupdate', function (event) {
        self.setState({
            timer: buzz.toTimer(this.getTime()) 
        });
    }).play();
}
```
Codepen
http://codepen.io/jaysalvat/pen/xEKyBA

## With fat arrow function

```javascript
componentWillMount() {        
    const sound = new buzz.sound('song.mp3');

    sound.bind('timeupdate', (event) => {
        this.setState({
            timer: buzz.toTimer(sound.getTime()) 
        });
    }).play();
}
```
Codepen
http://codepen.io/jaysalvat/pen/vXBVgZ

:)

**Comment by raygesualdo** [comment]
Good call. You're right. Thanks for the examples!

**Comment by jaysalvat** [comment]
You're welcome :)
