### ISSUE TITLE
MEDIA_ERR_SRC_NOT_SUPPORTED on iOS10

### ISSUE THREAD

**Issue by scarabdesign** [jaysalvat/buzz#108]
Happily using Buzz on all devices tried, but now after upgrading to iOS10, I'm getting MEDIA_ERR_SRC_NOT_SUPPORTED errors. Perhaps it's a streaming issue I'm having, however, my server supports 206 status, and the mime type in the header is set to audio/mpeg.

I'm not having a problem in iOS10 going to the Buzz demo page, but I'm thinking this is because your demo downloads all resources before playing, which is something my implementation cannot do. 

Just as a test, I was able to play this link in any web browser not on my iPhone, but in Mobile Safari I'm unable to play it:
http://buzz.jaysalvat.com/demo/sounds/truck.mp3

Indeed, this is most likely an Apple issue, but I'll buy you 3 beers if you help me solve it for us...

**Comment by scarabdesign** [comment]
I take it back; your audio file plays fine. It must be something with my server, but I can't tell what the issue is. It's a NodeJS server with Express 3. I'm sending the file with sendFile command. I'll let you know what I find.

**Comment by scarabdesign** [comment]
Interestingly, Mobile Safari on the iOS 10 Simulator streams my files just fine.

**Comment by scarabdesign** [comment]
Ok, so what I ended up doing was setting up nginx as a proxy to serve the files. I guess it's not ideal, but it works. Thanks again for the awesome library!

**Comment by jaysalvat** [comment]
Thanks for these feedbacks.
I guess it's not a Buzz bug :)
