### ISSUE TITLE
Mute does not work on iOS (cordova)

### ISSUE THREAD

**Issue by davidanquetin** [jaysalvat/buzz#109]
Hello, 

mySound.mute() or mySound.unmute() does not work on iOS (ipad / ios9.3.5)
App is generated by cordova.

play() and stop() are working well.
All is working well on Android and browser.

Even if I type it from safari console, mute function does not make effect.
Is it normal ?

Thanks.

**Comment by jaysalvat** [comment]
Hello @davidanquetin :)

I guess it's a mobile limitation like the volume level limitation.
Apple wants the volume to be controlled by the device's buttons.

Sorry, I can't fix it.

**Comment by davidanquetin** [comment]
ok thanks. What a shame.
