### ISSUE TITLE
filename.split is not a function

### ISSUE THREAD

**Issue by MaxwellGover** [jaysalvat/buzz#113]
<img width="1436" alt="screen shot 2017-06-11 at 3 54 50 pm" src="https://user-images.githubusercontent.com/11525891/27014042-713b446e-4ebe-11e7-8a93-e47126fe7d54.png">

Not sure what is causing this but getting this error whenever I try running the following code.

```
handleSongClick = (song) => {
    const currentSong = new buzz.sound(song);
    this.props.dispatch(getSongPath(song))
    currentSong.play();
    this.props.dispatch(isPlaying)
  }
```

**Comment by jaysalvat** [comment]
Hello! It seems song is not a string.
