### ISSUE TITLE
Using mySound.play() dont work

### ISSUE THREAD

**Issue by miyakedev** [jaysalvat/buzz#120]
I have the next code:
`    <script src="js/buzz.min.js"></script>
    <script>
        var mySound = new buzz.sound("sounds/vacillate", {
            formats: ["mp3"]
        });
        mySound.play();
    </script>`
and the sound does not play, any way to make the sound play once the page is loaded ?, I already tried
<body onload="myFunction"> or $(document).ready(function(){}}

**Comment by jaysalvat** [comment]
Sorry, browser don't allow sound to be played without a user interaction with the page first.

Try Google, it seems there are some workaround.
https://www.google.com/search?q=javascript+play+sound+without+user+interaction
