### ISSUE TITLE
List features in README

### ISSUE THREAD

**Issue by dandv** [jaysalvat/buzz#63]
I'm evaluating [sound/audio libraries](http://www.jsdb.io/audio/), and would be nice how Buzz stacks against [Sound Manager 2](https://github.com/scottschiller/SoundManager2), [Howler.js](http://github.com/goldfire/howler.js), [Sound JS](http://github.com/CreateJS/SoundJS) and [Audio5js](http://github.com/zohararad/audio5js).

**Comment by mitar** [comment]
@dandv: Can you tell me what was the result of your evaluation?
