### ISSUE TITLE
Add cdn info

### ISSUE THREAD

**Issue by PeterDaveHello** [jaysalvat/buzz#87]
Hi @jaysalvat,

I'm Peter from cdnjs.com,

I wonder if you would like to add cdn info in the readme?

This is the page we provide cdn for buzz - https://cdnjs.com/libraries/buzz

Thanks!

**Comment by jaysalvat** [comment]
Hello and thanks.

Question: How updates are managed?

Cheers :)

**Comment by PeterDaveHello** [comment]
Auto-update by the tags in the repo :)

**Comment by jaysalvat** [comment]
Done. Thanks :)

**Comment by PeterDaveHello** [comment]
Thank you.
