### ISSUE TITLE
fadeIn and out is invalid on android

### ISSUE THREAD

**Issue by gatspy** [jaysalvat/buzz#88]
I created a webapp by using buzz,but now i visit in the mobile browser,the music fadeIn and fadeOut effect is invalid.pls.

**Comment by jaysalvat** [comment]
Thanks for the feedback.
I have no Android to check. Sorry.

**Comment by jaysalvat** [comment]
It seems volume can not be set by javascript on mobile devices.
So FadeIn/out can't work.

Sorry.
