### ISSUE TITLE
buzz.js cant getDuration() in jquery.(document).ready

### ISSUE THREAD

**Issue by johnsonz** [jaysalvat/buzz#90]
I am using buzz.js libary and I am facing a weird problem. I just want to get the duration of the created sound like

var mySound = new buzz.sound("/sound/sound1.mp3"),
        timer = buzz.toTimer( mySound.getDuration() );
    $(".time").html(timer);
But it doesnt work. Im just getting "--" (the default) value.
It should work anyways - the same example is used in their documentation.

**Comment by johnsonz** [comment]
I have solved it. When I use the code below, it works well.
mysound.bind("loadeddata", function(e) {
   $('.time').html(buzz.toTimer(mysound.getDuration()));

**Comment by jaysalvat** [comment]
Hello,

    mySound.bind("timeupdate", function(e) {
        var timer = buzz.toTimer(this.getTime());
        document.getElementById("timer").innerHTML = timer;
    });

timeupdate is the event you need if you want it updated.
