### ISSUE TITLE
Not working on mobile chrome

### ISSUE THREAD

**Issue by guruganeshm** [jaysalvat/buzz#94]

**Comment by jaysalvat** [comment]
Ok.
Could you please tell me more?

Is the last version working?

**Comment by guruganeshm** [comment]
Hi Jay 
I used Buzz js via a package from the [https://atmospherejs.com/brentjanderson/buzz] (https://atmospherejs.com/brentjanderson/buzz) for a Meteor js Project, It works fine on desktop, but not on mobile, I don't know what's wrong here.

**Comment by mikob** [comment]
@jaysalvat recently, the library stopped working for the iPad (tested in mobile safari and chrome). In some cases it fails on safari on the desktop (like with the example below)... but I can get it working on safari for the desktop when the sound file is hosted locally. It's all quite perplexing :)

Interestingly, the demo still works in these cases. Here is a simple example with the latest 1.1.10 version, that doesn't work in mobile safari or mobile chrome on an iPad, but does work fine on the desktop AFAIK: http://jsbin.com/haluyoceza/1/edit

#80 #58

**Comment by jaysalvat** [comment]
Hello @mikob.

As Buzz doc says: 
http://buzz.jaysalvat.com/documentation/sound/
"* NOTE: In order to save bandwidth, mobile devices don't load/play sounds without user intervention (no autoplay). iPhone and iPad can only play one sound at a time and don't allow to change the volume dynamically. iPad has some issues with multiple sounds on the same page."

Try to trigger a sound with a click.

**Comment by guruganeshm** [comment]
Hi @jaysalvat .
Question regarding your latest comment above, by triggering with a click may increase weight to DOM Manipulation & I don't think that's a precise solution, what about Android browsers ?

**Comment by mikob** [comment]
@jaysalvat thank you. I somehow missed that page on the documentation. That answers all my questions. @guruganeshm it seems both safari and chrome mobile disable autoplay on any platform. Opera mobile might behave differently.

**Comment by jaysalvat** [comment]
Thanks guys.

As @mikob says both safari and chrome mobile disable autoplay on any platform.

So I close the issue :)

**Comment by guruganeshm** [comment]
@mikob  then what's the solution ? I don't have any idea, If you made it work on mobile devices somehow, please show me the code.
Thanks.

**Comment by jaysalvat** [comment]
There is no solution. Smartphones don't allow autoplay and autoload.
Can't do much on that.
An user interaction is required.

Sorry.
