### ISSUE TITLE
'sourceerror' event not documented

### ISSUE THREAD

**Issue by willstott101** [jaysalvat/buzz#98]
Took me a horribly long time to figure out why the `error` event never fires. Buzz forwards the `error` event from source elements to the buzz.sound object as `sourceerror`, and it seems the `audio` element only fires `error` if it has no source elements.

Only 'source error' gets logged for me on 'Chrome/43.0.2357.130' http://jsfiddle.net/avhagu1m/5/

Either `source` `error` events should be forwarded as `error` or the docs need updating. Docs don't appear to be in a repo though so I thought I'd just make an issue.

https://github.com/jaysalvat/buzz/blob/master/src/buzz.js#L629

**Comment by jaysalvat** [comment]
Thanks. Doc updated.
